#set(PEPPER_VISP_INTRINSIC_CAMERA_FILE "/home/jasiek/pepper-workspace/pepper-visual-servoing/config/pepper_cameras.xml"             CACHE STRING "")
#set(PEPPER_VISP_FOREHEAD_CONFIG_FILE  "/home/jasiek/pepper-workspace/pepper-visual-servoing/config/pepper_vs_forehead_config.yaml" CACHE STRING "")
#set(PEPPER_VISP_DATA_PATH             "/home/jasiek/pepper-workspace/pepper-visual-servoing/data/"                                 CACHE STRING "")
#set(PEPPER_VISP_LOG_VELOCITY          OFF                                                                                          CACHE BOOL   "")
#set(PEPPER_VISP_USE_PEPPER_CONTROLLER ON                                                                                           CACHE BOOL   "")
